name: SHOTPING Docker CD

on:
  pull_request:
    types:
      - closed
    branches: [main, develop]

jobs:
  cd:
    if: github.event.pull_request.merged == true

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Setting .env
        run: |
          echo "${{ secrets.ENV }}" >> .env

      - name: Build and Push docker images
        run: |
          docker-compose -f docker-compose.prod.yml build
          docker images
          docker-compose -f docker-compose.prod.yml push

      - name: Execute remote ssh commands to deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd shotping-docker
            git pull
            echo "${{ secrets.ENV }}" > .env
            echo "${{ secrets.ALERTMANAGER }}" > alertmanager.yml
            mkdir monitoring/alertmanager
            mv alertmanager.yml monitoring/alertmanager/
            docker-compose -f docker-compose.prod.yml down
            docker-compose -f docker-compose.prod.yml pull
            docker-compose -f docker-compose.prod.yml up -d
